### ISSUE TITLE
README Example not working // no deserialization of datetime

### ISSUE THREAD

**Issue by niniemann** [msiemens/tinydb-serialization#12]
Hey there!
Just trying the example from the readme already yields an error.

This:
```python
from tinydb.storages import JSONStorage # added. missing in readme.
from tinydb import TinyDB, Query
from tinydb_serialization import SerializationMiddleware
from tinydb_serialization.serializers import DateTimeSerializer

from datetime import datetime

serialization = SerializationMiddleware(JSONStorage)
serialization.register_serializer(DateTimeSerializer(), 'TinyDate')

db = TinyDB('db.json', storage=serialization)
db.insert({'date': datetime(2000, 1, 1, 12, 0, 0)})
db.all()
query = Query()
db.insert({'date': datetime(2010, 1, 1, 12, 0, 0)})
db.search(query.date > datetime(2005, 1, 1))
```

Does not execute:
```
Traceback (most recent call last):
  File "datetimetest.py", line 16, in <module>
    db.search(query.date > datetime(2005, 1, 1))
  File "[...]/env/lib/python3.6/site-packages/tinydb/table.py", line 233, in search
    docs = [doc for doc in self if cond(doc)]
  File "[...]/env/lib/python3.6/site-packages/tinydb/table.py", line 233, in <listcomp>
    docs = [doc for doc in self if cond(doc)]
  File "[...]/env/lib/python3.6/site-packages/tinydb/queries.py", line 59, in __call__
    return self._test(value)
  File "[...]/env/lib/python3.6/site-packages/tinydb/queries.py", line 203, in <lambda>
    lambda value: runner(value),
  File "[...]/env/lib/python3.6/site-packages/tinydb/queries.py", line 200, in runner
    return test(value)
  File "[...]/env/lib/python3.6/site-packages/tinydb/queries.py", line 268, in <lambda>
    lambda value: value > rhs,
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
```

Also, if I remove the query part and just
```python
print(db.all())
```
The I get a string instead of a datetime object.
```
[{'date': '{TinyDate}:2000-01-01T12:00:00'}]
```

Any ideas? 

tinydb version: 4.4.0
tinydb-serialization version: 2.1.0

**Comment by lyz-code** [comment]
It worked for me with Python 3.7.3

**Comment by msiemens** [comment]
I think Python 3.6 is causing the issue here. The `DateTimeSerializer` shipped with tinydb-serialization is not compatible with Python 3.6 as it relies on [`date.fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) which was introduced in Python 3.7. Could you try instead using the `DateTimeSerializer` from #6? It shoud run with Python 3.6 as far as I can see

**Comment by niniemann** [comment]
Yes, you are right! The `DateTimeSerializer` from #6 works. Thanks. :)
